; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

define i16 @add_rr(i16 %a, i16 %b) {
; CHECK-LABEL: add_rr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r2, r3
; CHECK-NEXT:    ret
  %r = add i16 %a, %b
  ret i16 %r
}

define i16 @add_ri(i16 %a) {
; CHECK-LABEL: add_ri:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r2, #1234
; CHECK-NEXT:    ret
  %r = add i16 %a, 1234
  ret i16 %r
}

define i16 @sub_rr(i16 %a, i16 %b) {
; CHECK-LABEL: sub_rr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r2, r3
; CHECK-NEXT:    ret
  %r = sub i16 %a, %b
  ret i16 %r
}

define i16 @and_or_xor(i16 %a, i16 %b) {
; CHECK-LABEL: and_or_xor:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    and r2, r3
; CHECK-NEXT:    or r2, #15
; CHECK-NEXT:    xor r2, r3
; CHECK-NEXT:    ret
  %1 = and i16 %a, %b
  %2 = or i16 %1, 15
  %3 = xor i16 %2, %b
  ret i16 %3
}

define i16 @not(i16 %a) {
; CHECK-LABEL: not:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    cpl r2
; CHECK-NEXT:    ret
  %r = xor i16 %a, -1
  ret i16 %r
}

define i16 @neg(i16 %a) {
; CHECK-LABEL: neg:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    neg r2
; CHECK-NEXT:    ret
  %r = sub i16 0, %a
  ret i16 %r
}

@word = external global i16

define i16 @add_absolute(i16 %a) {
; CHECK-LABEL: add_absolute:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r2, word
; CHECK-NEXT:    ret
  %v = load i16, ptr @word
  %r = add i16 %a, %v
  ret i16 %r
}
