; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; C166 has the full set of signed and unsigned condition codes, so every
; icmp maps onto a single cmp/jmpa pair.

define i16 @br_eq(i16 %a, i16 %b) {
; CHECK-LABEL: br_eq:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    cmp r2, r3
; CHECK-NEXT:    jmpr cc_NE, .LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %t
; CHECK-NEXT:    mov r2, #1
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_2: ; %f
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    ret
entry:
  %c = icmp eq i16 %a, %b
  br i1 %c, label %t, label %f
t:
  ret i16 1
f:
  ret i16 0
}

define i16 @br_slt(i16 %a, i16 %b) {
; CHECK-LABEL: br_slt:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    cmp r2, r3
; CHECK-NEXT:    jmpr cc_SGE, .LBB1_2
; CHECK-NEXT:  ; %bb.1: ; %t
; CHECK-NEXT:    mov r2, #1
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB1_2: ; %f
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    ret
entry:
  %c = icmp slt i16 %a, %b
  br i1 %c, label %t, label %f
t:
  ret i16 1
f:
  ret i16 0
}

define i16 @br_ugt(i16 %a, i16 %b) {
; CHECK-LABEL: br_ugt:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    cmp r2, r3
; CHECK-NEXT:    jmpr cc_ULE, .LBB2_2
; CHECK-NEXT:  ; %bb.1: ; %t
; CHECK-NEXT:    mov r2, #1
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB2_2: ; %f
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    ret
entry:
  %c = icmp ugt i16 %a, %b
  br i1 %c, label %t, label %f
t:
  ret i16 1
f:
  ret i16 0
}

define i16 @loop(i16 %n) {
; CHECK-LABEL: loop:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    mov r4, #0
; CHECK-NEXT:    cmp r4, r3
; CHECK-NEXT:    jmpr cc_SGE, .LBB3_2
; CHECK-NEXT:  .LBB3_1: ; %body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add r2, r4
; CHECK-NEXT:    add r4, #1
; CHECK-NEXT:    cmp r4, r3
; CHECK-NEXT:    jmpr cc_SLT, .LBB3_1
; CHECK-NEXT:  .LBB3_2: ; %exit
; CHECK-NEXT:    ret
entry:
  br label %head
head:
  %i = phi i16 [ 0, %entry ], [ %i2, %body ]
  %s = phi i16 [ 0, %entry ], [ %s2, %body ]
  %c = icmp slt i16 %i, %n
  br i1 %c, label %body, label %exit
body:
  %s2 = add i16 %s, %i
  %i2 = add i16 %i, 1
  br label %head
exit:
  ret i16 %s
}

define void @indirect_branch(ptr %target) {
; CHECK-LABEL: indirect_branch:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    jmpi cc_UC, [r2]
; CHECK-NEXT:  .LBB4_1: ; %b
; CHECK-NEXT:    ret
  indirectbr ptr %target, [ label %a, label %b ]
a:
  ret void
b:
  ret void
}
