; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; The shift instructions are word only, so a byte shift widens its operand and
; keeps the low byte of the result.  A left shift can leave the high byte
; alone, the right shifts have to fill it in first.

define i8 @shl_byte_imm(i8 %a) {
; CHECK-LABEL: shl_byte_imm:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    shl r2, #3
; CHECK-NEXT:    ret
  %r = shl i8 %a, 3
  ret i8 %r
}

define i8 @lshr_byte_imm(i8 %a) {
; CHECK-LABEL: lshr_byte_imm:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movbz r2, rl2
; CHECK-NEXT:    shr r2, #3
; CHECK-NEXT:    ret
  %r = lshr i8 %a, 3
  ret i8 %r
}

define i8 @ashr_byte_imm(i8 %a) {
; CHECK-LABEL: ashr_byte_imm:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movbs r2, rl2
; CHECK-NEXT:    ashr r2, #1
; CHECK-NEXT:    ret
  %r = ashr i8 %a, 1
  ret i8 %r
}

define i8 @shl_byte_reg(i8 %a, i8 %b) {
; CHECK-LABEL: shl_byte_reg:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    and r3, #255
; CHECK-NEXT:    shl r2, r3
; CHECK-NEXT:    ret
  %r = shl i8 %a, %b
  ret i8 %r
}

define i8 @ashr_byte_reg(i8 %a, i8 %b) {
; CHECK-LABEL: ashr_byte_reg:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    and r3, #255
; CHECK-NEXT:    movbs r2, rl2
; CHECK-NEXT:    ashr r2, r3
; CHECK-NEXT:    ret
  %r = ashr i8 %a, %b
  ret i8 %r
}
