; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

define i8 @load_byte(ptr %p) {
; CHECK-LABEL: load_byte:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movb rl2, [r2]
; CHECK-NEXT:    ret
  %v = load i8, ptr %p
  ret i8 %v
}

define void @store_byte(ptr %p, i8 %v) {
; CHECK-LABEL: store_byte:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movb [r2+#0], rl3
; CHECK-NEXT:    ret
  store i8 %v, ptr %p
  ret void
}

define i16 @zext_byte(ptr %p) {
; CHECK-LABEL: zext_byte:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movb rl2, [r2]
; CHECK-NEXT:    movbz r2, rl2
; CHECK-NEXT:    ret
  %v = load i8, ptr %p
  %z = zext i8 %v to i16
  ret i16 %z
}

define i16 @sext_byte(ptr %p) {
; CHECK-LABEL: sext_byte:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movb rl2, [r2]
; CHECK-NEXT:    movbs r2, rl2
; CHECK-NEXT:    ret
  %v = load i8, ptr %p
  %s = sext i8 %v to i16
  ret i16 %s
}

define void @truncating_store(ptr %p, i16 %v) {
; CHECK-LABEL: truncating_store:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movb [r2+#0], rl3
; CHECK-NEXT:    ret
  %t = trunc i16 %v to i8
  store i8 %t, ptr %p
  ret void
}

define i8 @byte_alu(i8 %a, i8 %b) {
; CHECK-LABEL: byte_alu:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    addb rl2, rl3
; CHECK-NEXT:    andb rl2, #15
; CHECK-NEXT:    xorb rl2, rl3
; CHECK-NEXT:    ret
  %1 = add i8 %a, %b
  %2 = and i8 %1, 15
  %3 = xor i8 %2, %b
  ret i8 %3
}
