; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; The first four words are passed in R2-R5, the rest on the ABI stack in R0.

declare i16 @four(i16, i16, i16, i16)
declare i16 @six(i16, i16, i16, i16, i16, i16)

define i16 @call_in_regs(i16 %a) {
; CHECK-LABEL: call_in_regs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r3, #2
; CHECK-NEXT:    mov r4, #3
; CHECK-NEXT:    mov r5, #4
; CHECK-NEXT:    calla cc_UC, four
; CHECK-NEXT:    ret
  %r = call i16 @four(i16 %a, i16 2, i16 3, i16 4)
  ret i16 %r
}

define i16 @call_with_stack_args(i16 %a) {
; CHECK-LABEL: call_with_stack_args:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r0, #4
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    mov r3, #6
; CHECK-NEXT:    mov [r0+#2], r3
; CHECK-NEXT:    mov r3, #5
; CHECK-NEXT:    mov [r0], r3
; CHECK-NEXT:    mov r3, #2
; CHECK-NEXT:    mov r4, #3
; CHECK-NEXT:    mov r5, #4
; CHECK-NEXT:    calla cc_UC, six
; CHECK-NEXT:    add r0, #4
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    ret
  %r = call i16 @six(i16 %a, i16 2, i16 3, i16 4, i16 5, i16 6)
  ret i16 %r
}

define i16 @call_indirect(ptr %f, i16 %x) {
; CHECK-LABEL: call_indirect:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    mov r2, r3
; CHECK-NEXT:    calli cc_UC, [r4]
; CHECK-NEXT:    ret
  %r = call i16 %f(i16 %x)
  ret i16 %r
}

define i16 @incoming_stack_arg(i16 %a, i16 %b, i16 %c, i16 %d, i16 %e) {
; CHECK-LABEL: incoming_stack_arg:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r3, [r0]
; CHECK-NEXT:    add r2, r3
; CHECK-NEXT:    ret
  %r = add i16 %a, %e
  ret i16 %r
}
