; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; A function carrying the "far" attribute lives in another segment, so it is
; entered with CALLS and left with RETS: both push and pop the code segment
; pointer along with the instruction pointer.

declare i16 @far_callee(i16) "far"
declare i16 @near_callee(i16)

define i16 @call_far(i16 %x) {
; CHECK-LABEL: call_far:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    calls #seg(far_callee), sof(far_callee)
; CHECK-NEXT:    ret
  %r = call i16 @far_callee(i16 %x)
  ret i16 %r
}

define i16 @call_near(i16 %x) {
; CHECK-LABEL: call_near:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    calla cc_UC, near_callee
; CHECK-NEXT:    ret
  %r = call i16 @near_callee(i16 %x)
  ret i16 %r
}

define i16 @is_far(i16 %x) "far" {
; CHECK-LABEL: is_far:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x04 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    add r2, #1
; CHECK-NEXT:    rets
  %r = add i16 %x, 1
  ret i16 %r
}

; An interrupt handler is entered by the hardware rather than by a CALLS, so it
; still returns with RETI wherever it was placed.
define void @far_interrupt() "far" "interrupt" {
; CHECK-LABEL: far_interrupt:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    reti
  ret void
}
