; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; The C library's block moves take near pointers, so one that touches the far
; address space goes to an entry point of its own instead.  A near operand is
; widened on the way in.

declare void @llvm.memcpy.p1.p1.i16(ptr addrspace(1), ptr addrspace(1), i16, i1)
declare void @llvm.memcpy.p1.p0.i16(ptr addrspace(1), ptr, i16, i1)
declare void @llvm.memmove.p1.p1.i16(ptr addrspace(1), ptr addrspace(1), i16, i1)
declare void @llvm.memset.p1.i16(ptr addrspace(1), i8, i16, i1)
declare void @llvm.memcpy.p0.p0.i16(ptr, ptr, i16, i1)

define void @far_memcpy(ptr addrspace(1) %d, ptr addrspace(1) %s, i16 %n) {
; CHECK-LABEL: far_memcpy:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    calla cc_UC, __memcpy_far
; CHECK-NEXT:    ret
  call void @llvm.memcpy.p1.p1.i16(ptr addrspace(1) %d, ptr addrspace(1) %s, i16 %n, i1 false)
  ret void
}

define void @mixed_memcpy(ptr addrspace(1) %d, ptr %s, i16 %n) {
; CHECK-LABEL: mixed_memcpy:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r6, r5
; CHECK-NEXT:    mov r5, #0
; CHECK-NEXT:    calla cc_UC, __memcpy_far
; CHECK-NEXT:    ret
  call void @llvm.memcpy.p1.p0.i16(ptr addrspace(1) %d, ptr %s, i16 %n, i1 false)
  ret void
}

define void @far_memmove(ptr addrspace(1) %d, ptr addrspace(1) %s, i16 %n) {
; CHECK-LABEL: far_memmove:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    calla cc_UC, __memmove_far
; CHECK-NEXT:    ret
  call void @llvm.memmove.p1.p1.i16(ptr addrspace(1) %d, ptr addrspace(1) %s, i16 %n, i1 false)
  ret void
}

define void @far_memset(ptr addrspace(1) %d, i8 %c, i16 %n) {
; CHECK-LABEL: far_memset:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    and r4, #255
; CHECK-NEXT:    calla cc_UC, __memset_far
; CHECK-NEXT:    ret
  call void @llvm.memset.p1.i16(ptr addrspace(1) %d, i8 %c, i16 %n, i1 false)
  ret void
}

; A move that stays near is untouched.
define void @near_memcpy(ptr %d, ptr %s, i16 %n) {
; CHECK-LABEL: near_memcpy:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    calla cc_UC, memcpy
; CHECK-NEXT:    ret
  call void @llvm.memcpy.p0.p0.i16(ptr %d, ptr %s, i16 %n, i1 false)
  ret void
}
