; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; Address space 1 holds far pointers: a linear 24 bit address zero extended
; into 32 bits.  An access through one names its segment in an EXTS covering
; exactly the instruction that follows, so the two must stay adjacent.

@g = global i16 42
@fg = addrspace(1) global i16 7

define i16 @far_load(ptr addrspace(1) %p) {
; CHECK-LABEL: far_load:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov r2, [r2]
; CHECK-NEXT:    ret
  %v = load i16, ptr addrspace(1) %p
  ret i16 %v
}

define void @far_store(ptr addrspace(1) %p, i16 %v) {
; CHECK-LABEL: far_store:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov [r2], r4
; CHECK-NEXT:    ret
  store i16 %v, ptr addrspace(1) %p
  ret void
}

define zeroext i8 @far_load_byte(ptr addrspace(1) %p) {
; CHECK-LABEL: far_load_byte:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    movb rl2, [r2]
; CHECK-NEXT:    movbz r2, rl2
; CHECK-NEXT:    ret
  %v = load i8, ptr addrspace(1) %p
  ret i8 %v
}

define void @far_store_byte(ptr addrspace(1) %p, i8 %v) {
; CHECK-LABEL: far_store_byte:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    movb [r2], rl4
; CHECK-NEXT:    ret
  store i8 %v, ptr addrspace(1) %p
  ret void
}

; A word wider than the bus is split by the generic legalizer first, and the
; carry out of the offset has to reach the segment.
define i32 @far_load_i32(ptr addrspace(1) %p) {
; CHECK-LABEL: far_load_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov r4, [r2]
; CHECK-NEXT:    add r2, #2
; CHECK-NEXT:    addc r3, #0
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov r3, [r2]
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    ret
  %v = load i32, ptr addrspace(1) %p
  ret i32 %v
}

; Indexing is plain 32 bit arithmetic, so it crosses segment boundaries.
define i16 @far_index(ptr addrspace(1) %p, i16 %i) {
; CHECK-LABEL: far_index:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r5, r4
; CHECK-NEXT:    shl r5, #1
; CHECK-NEXT:    shr r4, #15
; CHECK-NEXT:    add r5, r2
; CHECK-NEXT:    addc r4, r3
; CHECK-NEXT:    exts r4, #1
; CHECK-NEXT:    mov r2, [r5]
; CHECK-NEXT:    ret
  %e = zext i16 %i to i32
  %q = getelementptr i16, ptr addrspace(1) %p, i32 %e
  %v = load i16, ptr addrspace(1) %q
  ret i16 %v
}

; Widening a near pointer relies on the reset mapping of the data page
; pointers, where a 16 bit address is the same physical address in segment 0.
define ptr addrspace(1) @to_far(ptr %p) {
; CHECK-LABEL: to_far:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r3, #0
; CHECK-NEXT:    ret
  %f = addrspacecast ptr %p to ptr addrspace(1)
  ret ptr addrspace(1) %f
}

define ptr @to_near(ptr addrspace(1) %p) {
; CHECK-LABEL: to_near:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ret
  %n = addrspacecast ptr addrspace(1) %p to ptr
  ret ptr %n
}

; A near global reached through a far pointer needs no relocation for its
; segment: it is always in segment 0.
define i16 @far_load_global() {
; CHECK-LABEL: far_load_global:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    mov r3, #g
; CHECK-NEXT:    exts r2, #1
; CHECK-NEXT:    mov r2, [r3]
; CHECK-NEXT:    ret
  %f = addrspacecast ptr @g to ptr addrspace(1)
  %v = load i16, ptr addrspace(1) %f
  ret i16 %v
}

; An object declared in the far address space is built from two relocations,
; and the segment goes straight into the EXTS rather than a register.
define i16 @far_global() {
; CHECK-LABEL: far_global:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts #seg(fg), #1
; CHECK-NEXT:    mov r2, sof(fg)
; CHECK-NEXT:    ret
  %v = load i16, ptr addrspace(1) @fg
  ret i16 %v
}

define void @far_global_store(i16 %v) {
; CHECK-LABEL: far_global_store:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts #seg(fg), #1
; CHECK-NEXT:    mov sof(fg), r2
; CHECK-NEXT:    ret
  store i16 %v, ptr addrspace(1) @fg
  ret void
}

; The offset still has to be computed when it is not the symbol itself.
define i16 @far_global_indexed(i16 %i) {
; CHECK-LABEL: far_global_indexed:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    shl r3, #1
; CHECK-NEXT:    shr r2, #15
; CHECK-NEXT:    mov r4, #sof(fg)
; CHECK-NEXT:    mov r5, #seg(fg)
; CHECK-NEXT:    add r4, r3
; CHECK-NEXT:    addc r5, r2
; CHECK-NEXT:    exts r5, #1
; CHECK-NEXT:    mov r2, [r4]
; CHECK-NEXT:    ret
  %e = zext i16 %i to i32
  %q = getelementptr i16, ptr addrspace(1) @fg, i32 %e
  %v = load i16, ptr addrspace(1) %q
  ret i16 %v
}

; A constant offset into a far object belongs to its address rather than being
; arithmetic on it, since both relocations carry an addend.
@fa = addrspace(1) global [4 x i16] zeroinitializer

define i16 @far_global_field() {
; CHECK-LABEL: far_global_field:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts #seg(fa+4), #1
; CHECK-NEXT:    mov r2, sof(fa+4)
; CHECK-NEXT:    ret
  %v = load i16, ptr addrspace(1) getelementptr inbounds ([4 x i16], ptr addrspace(1) @fa, i32 0, i32 2)
  ret i16 %v
}

; A near global reached through a cast is a different thing: the offset is
; added to the 16 bit address, which the cast then widens, and folding it into
; the symbol would only be right if that addition could not wrap.
@na = global [4 x i16] zeroinitializer

define i16 @cast_global_field() {
; CHECK-LABEL: cast_global_field:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, #na
; CHECK-NEXT:    mov r3, #0
; CHECK-NEXT:    add r2, #4
; CHECK-NEXT:    addc r3, #0
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov r2, [r2]
; CHECK-NEXT:    ret
  %f = addrspacecast ptr @na to ptr addrspace(1)
  %p = getelementptr [4 x i16], ptr addrspace(1) %f, i32 0, i32 2
  %v = load i16, ptr addrspace(1) %p
  ret i16 %v
}
