; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=c166 -verify-machineinstrs -frame-pointer=all < %s \
; RUN:   | FileCheck %s --check-prefix=FP

; The ABI stack pointer lives in R0 and the frame pointer, when one is needed,
; in R1.  Return addresses stay on the separate hardware stack.

declare void @use(ptr)

define void @locals() {
; CHECK-LABEL: locals:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r0, #20
; CHECK-NEXT:    .cfi_def_cfa_offset 20
; CHECK-NEXT:    mov r2, r0
; CHECK-NEXT:    calla cc_UC, use
; CHECK-NEXT:    add r0, #20
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    ret
;
; FP-LABEL: locals:
; FP:       ; %bb.0:
; FP-NEXT:    sub r0, #22
; FP-NEXT:    .cfi_def_cfa_offset 22
; FP-NEXT:    mov [r0+#20], r1 ; 2-byte Folded Spill
; FP-NEXT:    .cfi_offset r1, -2
; FP-NEXT:    mov r1, r0
; FP-NEXT:    .cfi_def_cfa_register r1
; FP-NEXT:    mov r2, r1
; FP-NEXT:    calla cc_UC, use
; FP-NEXT:    mov r0, r1
; FP-NEXT:    mov r1, [r0+#20] ; 2-byte Folded Reload
; FP-NEXT:    add r0, #22
; FP-NEXT:    .cfi_def_cfa r0, 0
; FP-NEXT:    ret
  %p = alloca [10 x i16]
  call void @use(ptr %p)
  ret void
}

define i16 @dynamic_alloca(i16 %n) {
; CHECK-LABEL: dynamic_alloca:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r0, #2
; CHECK-NEXT:    .cfi_def_cfa_offset 2
; CHECK-NEXT:    mov [r0], r1 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r1, -2
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    .cfi_def_cfa_register r1
; CHECK-NEXT:    shl r2, #1
; CHECK-NEXT:    mov r3, r0
; CHECK-NEXT:    sub r3, r2
; CHECK-NEXT:    mov r0, r3
; CHECK-NEXT:    mov r2, #7
; CHECK-NEXT:    mov [r3], r2
; CHECK-NEXT:    mov r0, r1
; CHECK-NEXT:    mov r1, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #2
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    ret
;
; FP-LABEL: dynamic_alloca:
; FP:       ; %bb.0:
; FP-NEXT:    sub r0, #2
; FP-NEXT:    .cfi_def_cfa_offset 2
; FP-NEXT:    mov [r0], r1 ; 2-byte Folded Spill
; FP-NEXT:    .cfi_offset r1, -2
; FP-NEXT:    mov r1, r0
; FP-NEXT:    .cfi_def_cfa_register r1
; FP-NEXT:    shl r2, #1
; FP-NEXT:    mov r3, r0
; FP-NEXT:    sub r3, r2
; FP-NEXT:    mov r0, r3
; FP-NEXT:    mov r2, #7
; FP-NEXT:    mov [r3], r2
; FP-NEXT:    mov r0, r1
; FP-NEXT:    mov r1, [r0] ; 2-byte Folded Reload
; FP-NEXT:    add r0, #2
; FP-NEXT:    .cfi_def_cfa r0, 0
; FP-NEXT:    ret
  %p = alloca i16, i16 %n
  store i16 7, ptr %p
  %v = load i16, ptr %p
  ret i16 %v
}

define i16 @callee_saved(i16 %a, i16 %b, i16 %c, i16 %d) {
; CHECK-LABEL: callee_saved:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r0, #8
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    mov [r0+#6], r12 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#4], r13 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#2], r14 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0], r15 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r12, -2
; CHECK-NEXT:    .cfi_offset r13, -4
; CHECK-NEXT:    .cfi_offset r14, -6
; CHECK-NEXT:    .cfi_offset r15, -8
; CHECK-NEXT:    mov r12, r5
; CHECK-NEXT:    mov r13, r4
; CHECK-NEXT:    mov r14, r3
; CHECK-NEXT:    mov r15, r2
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    calla cc_UC, use
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    calla cc_UC, use
; CHECK-NEXT:    mul r13, r12
; CHECK-NEXT:    mov r2, mdl
; CHECK-NEXT:    mul r15, r14
; CHECK-NEXT:    mov r3, mdl
; CHECK-NEXT:    mov r4, r3
; CHECK-NEXT:    add r4, r2
; CHECK-NEXT:    mul r3, r2
; CHECK-NEXT:    mov r2, mdl
; CHECK-NEXT:    sub r2, r4
; CHECK-NEXT:    mov r15, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r14, [r0+#2] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r13, [r0+#4] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r12, [r0+#6] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #8
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    ret
;
; FP-LABEL: callee_saved:
; FP:       ; %bb.0:
; FP-NEXT:    sub r0, #10
; FP-NEXT:    .cfi_def_cfa_offset 10
; FP-NEXT:    mov [r0+#8], r1 ; 2-byte Folded Spill
; FP-NEXT:    mov [r0+#6], r12 ; 2-byte Folded Spill
; FP-NEXT:    mov [r0+#4], r13 ; 2-byte Folded Spill
; FP-NEXT:    mov [r0+#2], r14 ; 2-byte Folded Spill
; FP-NEXT:    mov [r0], r15 ; 2-byte Folded Spill
; FP-NEXT:    .cfi_offset r1, -2
; FP-NEXT:    .cfi_offset r12, -4
; FP-NEXT:    .cfi_offset r13, -6
; FP-NEXT:    .cfi_offset r14, -8
; FP-NEXT:    .cfi_offset r15, -10
; FP-NEXT:    mov r1, r0
; FP-NEXT:    .cfi_def_cfa_register r1
; FP-NEXT:    mov r12, r5
; FP-NEXT:    mov r13, r4
; FP-NEXT:    mov r14, r3
; FP-NEXT:    mov r15, r2
; FP-NEXT:    mov r2, #0
; FP-NEXT:    calla cc_UC, use
; FP-NEXT:    mov r2, #0
; FP-NEXT:    calla cc_UC, use
; FP-NEXT:    mul r13, r12
; FP-NEXT:    mov r2, mdl
; FP-NEXT:    mul r15, r14
; FP-NEXT:    mov r3, mdl
; FP-NEXT:    mov r4, r3
; FP-NEXT:    add r4, r2
; FP-NEXT:    mul r3, r2
; FP-NEXT:    mov r2, mdl
; FP-NEXT:    sub r2, r4
; FP-NEXT:    mov r0, r1
; FP-NEXT:    mov r15, [r0] ; 2-byte Folded Reload
; FP-NEXT:    mov r14, [r0+#2] ; 2-byte Folded Reload
; FP-NEXT:    mov r13, [r0+#4] ; 2-byte Folded Reload
; FP-NEXT:    mov r12, [r0+#6] ; 2-byte Folded Reload
; FP-NEXT:    mov r1, [r0+#8] ; 2-byte Folded Reload
; FP-NEXT:    add r0, #10
; FP-NEXT:    .cfi_def_cfa r0, 0
; FP-NEXT:    ret
  %1 = mul i16 %a, %b
  %2 = mul i16 %c, %d
  %3 = mul i16 %1, %2
  call void @use(ptr null)
  %4 = add i16 %1, %2
  call void @use(ptr null)
  %5 = sub i16 %3, %4
  ret i16 %5
}
