; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; A constant offset from a global folds into the absolute "mem" operand.

%S = type { i16, i16, i16 }
@s = global %S zeroinitializer
@arr = global [8 x i16] zeroinitializer

define i16 @load_field() {
; CHECK-LABEL: load_field:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, s+2
; CHECK-NEXT:    ret
  %p = getelementptr %S, ptr @s, i16 0, i32 1
  %v = load i16, ptr %p
  ret i16 %v
}

define void @store_field(i16 %x) {
; CHECK-LABEL: store_field:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov s+4, r2
; CHECK-NEXT:    ret
  %p = getelementptr %S, ptr @s, i16 0, i32 2
  store i16 %x, ptr %p
  ret void
}

define i16 @load_element() {
; CHECK-LABEL: load_element:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, arr+10
; CHECK-NEXT:    ret
  %p = getelementptr [8 x i16], ptr @arr, i16 0, i16 5
  %v = load i16, ptr %p
  ret i16 %v
}

; A fixed address is printed as the number it is.  FFC0H is port 2, which is
; not one of the registers the backend models.
define i16 @load_from_fixed_address() {
; CHECK-LABEL: load_from_fixed_address:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, 65472
; CHECK-NEXT:    ret
  %v = load volatile i16, ptr inttoptr (i16 -64 to ptr)
  ret i16 %v
}

; One that is, though, is named: the assembler reads the name back as the same
; address, so this still assembles to what it came from.  FE00H is DPP0.
define i16 @load_from_sfr() {
; CHECK-LABEL: load_from_sfr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, dpp0
; CHECK-NEXT:    ret
  %v = load volatile i16, ptr inttoptr (i16 -512 to ptr)
  ret i16 %v
}

define i16 @add_field(i16 %x) {
; CHECK-LABEL: add_field:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r2, s+2
; CHECK-NEXT:    ret
  %p = getelementptr %S, ptr @s, i16 0, i32 1
  %v = load i16, ptr %p
  %r = add i16 %x, %v
  ret i16 %r
}
