; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; A function marked with the "interrupt" attribute returns with RETI.

@count = global i16 0

define void @isr() #0 {
; CHECK-LABEL: isr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    sub r0, #2
; CHECK-NEXT:    .cfi_def_cfa_offset 2
; CHECK-NEXT:    mov [r0], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r2, -2
; CHECK-NEXT:    mov r2, #1
; CHECK-NEXT:    add count, r2
; CHECK-NEXT:    mov r2, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #2
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    reti
  %v = load volatile i16, ptr @count
  %n = add i16 %v, 1
  store volatile i16 %n, ptr @count
  ret void
}

; An interrupt handler has to put back everything it touches, including the
; registers a normal function is free to clobber.
declare void @helper()

define void @isr_with_call() #0 {
; CHECK-LABEL: isr_with_call:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    push mdc
; CHECK-NEXT:    push mdl
; CHECK-NEXT:    push mdh
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x08, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x06, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x0c ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x08 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x0a ; caller's PSW
; CHECK-NEXT:    sub r0, #20
; CHECK-NEXT:    .cfi_def_cfa_offset 20
; CHECK-NEXT:    mov [r0+#18], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#16], r3 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#14], r4 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#12], r5 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#10], r6 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#8], r7 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#6], r8 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#4], r9 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#2], r10 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0], r11 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r2, -2
; CHECK-NEXT:    .cfi_offset r3, -4
; CHECK-NEXT:    .cfi_offset r4, -6
; CHECK-NEXT:    .cfi_offset r5, -8
; CHECK-NEXT:    .cfi_offset r6, -10
; CHECK-NEXT:    .cfi_offset r7, -12
; CHECK-NEXT:    .cfi_offset r8, -14
; CHECK-NEXT:    .cfi_offset r9, -16
; CHECK-NEXT:    .cfi_offset r10, -18
; CHECK-NEXT:    .cfi_offset r11, -20
; CHECK-NEXT:    calla cc_UC, helper
; CHECK-NEXT:    mov r11, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r10, [r0+#2] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r9, [r0+#4] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r8, [r0+#6] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r7, [r0+#8] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r6, [r0+#10] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r5, [r0+#12] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r4, [r0+#14] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r3, [r0+#16] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r2, [r0+#18] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #20
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    pop mdh
; CHECK-NEXT:    pop mdl
; CHECK-NEXT:    pop mdc
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    reti
  call void @helper()
  ret void
}

define void @normal() {
; CHECK-LABEL: normal:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ret
  ret void
}

; A multiplication or a division is interrupted part way through rather than
; run to completion, so a handler that uses the multiply/divide unit has to put
; MDL, MDH and MDC back.  MDC is saved first and restored last: reading MDL,
; which is what pushing it does, clears MDC.MDRIU.
define void @isr_multiplies() #0 {
; CHECK-LABEL: isr_multiplies:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    push mdc
; CHECK-NEXT:    push mdl
; CHECK-NEXT:    push mdh
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x08, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x06, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x0c ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x08 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x0a ; caller's PSW
; CHECK-NEXT:    sub r0, #4
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    mov [r0+#2], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0], r3 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r2, -2
; CHECK-NEXT:    .cfi_offset r3, -4
; CHECK-NEXT:    mov r2, #3
; CHECK-NEXT:    mov r3, count
; CHECK-NEXT:    mul r3, r2
; CHECK-NEXT:    mov r2, mdl
; CHECK-NEXT:    mov count, r2
; CHECK-NEXT:    mov r3, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r2, [r0+#2] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #4
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    pop mdh
; CHECK-NEXT:    pop mdl
; CHECK-NEXT:    pop mdc
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    reti
  %v = load volatile i16, ptr @count
  %n = mul i16 %v, 3
  store volatile i16 %n, ptr @count
  ret void
}

define void @isr_divides(i16 %d) #0 {
; CHECK-LABEL: isr_divides:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    push mdc
; CHECK-NEXT:    push mdl
; CHECK-NEXT:    push mdh
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x08, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x06, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x0c ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x08 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x0a ; caller's PSW
; CHECK-NEXT:    sub r0, #4
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    mov [r0+#2], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0], r3 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r2, -2
; CHECK-NEXT:    .cfi_offset r3, -4
; CHECK-NEXT:    mov r3, count
; CHECK-NEXT:    mov mdl, r3
; CHECK-NEXT:    div r2
; CHECK-NEXT:    mov r2, mdl
; CHECK-NEXT:    mov count, r2
; CHECK-NEXT:    mov r3, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r2, [r0+#2] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #4
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    pop mdh
; CHECK-NEXT:    pop mdl
; CHECK-NEXT:    pop mdc
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    reti
  %v = load volatile i16, ptr @count
  %n = sdiv i16 %v, %d
  store volatile i16 %n, ptr @count
  ret void
}

; A normal function is not responsible for its caller's multiply/divide state.
define i16 @normal_multiplies(i16 %a, i16 %b) {
; CHECK-LABEL: normal_multiplies:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mul r2, r3
; CHECK-NEXT:    mov r2, mdl
; CHECK-NEXT:    ret
  %m = mul i16 %a, %b
  ret i16 %m
}

; A handler that takes an argument saves that register as a callee saved one
; while it is still carrying the incoming value, so the spill must not claim to
; be the end of its life.
define void @isr_with_argument(i16 %v) #0 {
; CHECK-LABEL: isr_with_argument:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    add count, r2
; CHECK-NEXT:    reti
  %c = load volatile i16, ptr @count
  %n = add i16 %c, %v
  store volatile i16 %n, ptr @count
  ret void
}

attributes #0 = { "interrupt" }
