; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -mattr=+mac -verify-machineinstrs < %s | FileCheck %s

; The CPU preserves nothing of the coprocessor across an interrupt: the C166S
; V2 manual says "all dedicated MAC registers must be saved on the stack if the
; MAC unit is shared between different tasks and interrupts".  So a handler
; that uses it saves it, exactly as it does the multiply/divide unit.
;
; The accumulator is forty bits, which is why MSW is in the set: its low byte
; is MAE, the top eight.  And writing a word to MAH zeroes MAL and sign extends
; MAE, so MAH has to come back first, with MAL and MSW landing on top of what
; that cleared - which makes the push order MSW, MAL, MAH and the pop order its
; mirror.

@x = global i16 0
@y = global i16 0
@accum = global i32 0

define void @mac_isr() #0 {
; CHECK-LABEL: mac_isr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    push msw
; CHECK-NEXT:    push mal
; CHECK-NEXT:    push mah
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x08, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x06, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x0c ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x08 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x0a ; caller's PSW
; CHECK-NEXT:    sub r0, #8
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    mov [r0+#6], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#4], r3 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#2], r4 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0], r5 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r2, -2
; CHECK-NEXT:    .cfi_offset r3, -4
; CHECK-NEXT:    .cfi_offset r4, -6
; CHECK-NEXT:    .cfi_offset r5, -8
; CHECK-NEXT:    mov r2, x
; CHECK-NEXT:    mov r3, y
; CHECK-NEXT:    mov r4, accum+2
; CHECK-NEXT:    mov r5, accum
; CHECK-NEXT:    coload r5, r4
; CHECK-NEXT:    comac r3, r2
; CHECK-NEXT:    costore r2, mal
; CHECK-NEXT:    costore r3, mah
; CHECK-NEXT:    mov accum+2, r3
; CHECK-NEXT:    mov accum, r2
; CHECK-NEXT:    mov r5, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r4, [r0+#2] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r3, [r0+#4] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r2, [r0+#6] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #8
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    pop mah
; CHECK-NEXT:    pop mal
; CHECK-NEXT:    pop msw
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    reti
  %a = load volatile i16, ptr @x
  %sa = sext i16 %a to i32
  %b = load volatile i16, ptr @y
  %sb = sext i16 %b to i32
  %mul = mul nsw i32 %sb, %sa
  %acc = load volatile i32, ptr @accum
  %sum = add nsw i32 %mul, %acc
  store volatile i32 %sum, ptr @accum
  ret void
}

; A handler that never reaches the coprocessor pays nothing for it.
define void @plain_isr() #0 {
; CHECK-LABEL: plain_isr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    sub r0, #2
; CHECK-NEXT:    .cfi_def_cfa_offset 2
; CHECK-NEXT:    mov [r0], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r2, -2
; CHECK-NEXT:    mov r2, #1
; CHECK-NEXT:    add x, r2
; CHECK-NEXT:    mov r2, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #2
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    reti
  %v = load volatile i16, ptr @x
  %n = add i16 %v, 1
  store volatile i16 %n, ptr @x
  ret void
}

; Nor does an ordinary function, which is not interrupting anything.
define i32 @not_an_isr(i16 %a, i16 %b, i32 %acc) {
; CHECK-LABEL: not_an_isr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    coload r4, r5
; CHECK-NEXT:    comac r3, r2
; CHECK-NEXT:    costore r2, mal
; CHECK-NEXT:    costore r3, mah
; CHECK-NEXT:    ret
  %sa = sext i16 %a to i32
  %sb = sext i16 %b to i32
  %mul = mul nsw i32 %sb, %sa
  %sum = add nsw i32 %mul, %acc
  ret i32 %sum
}

attributes #0 = { "interrupt" }
