; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; A function marked with the "interrupt" attribute returns with RETI.

@count = global i16 0

define void @isr() #0 {
; CHECK-LABEL: isr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r0, #2
; CHECK-NEXT:    .cfi_def_cfa_offset 2
; CHECK-NEXT:    mov [r0], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    mov r2, #1
; CHECK-NEXT:    add r2, count
; CHECK-NEXT:    mov count, r2
; CHECK-NEXT:    mov r2, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #2
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    reti
  %v = load volatile i16, ptr @count
  %n = add i16 %v, 1
  store volatile i16 %n, ptr @count
  ret void
}

; An interrupt handler has to put back everything it touches, including the
; registers a normal function is free to clobber.
declare void @helper()

define void @isr_with_call() #0 {
; CHECK-LABEL: isr_with_call:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r0, #20
; CHECK-NEXT:    .cfi_def_cfa_offset 20
; CHECK-NEXT:    mov [r0+#18], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#16], r3 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#14], r4 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#12], r5 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#10], r6 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#8], r7 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#6], r8 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#4], r9 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#2], r10 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0], r11 ; 2-byte Folded Spill
; CHECK-NEXT:    calla cc_UC, helper
; CHECK-NEXT:    mov r11, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r10, [r0+#2] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r9, [r0+#4] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r8, [r0+#6] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r7, [r0+#8] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r6, [r0+#10] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r5, [r0+#12] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r4, [r0+#14] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r3, [r0+#16] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r2, [r0+#18] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #20
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    reti
  call void @helper()
  ret void
}

define void @normal() {
; CHECK-LABEL: normal:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ret
  ret void
}

attributes #0 = { "interrupt" }
