; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; A dense switch becomes a table of 16 bit block addresses indexed by the
; scaled selector.  The table's address is a relocatable constant, so it rides
; in the displacement of the load rather than being built in a register.

define i16 @dense(i16 %x) {
; CHECK-LABEL: dense:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    cmp r2, #5
; CHECK-NEXT:    jmpr cc_UGT, .LBB0_8
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    shl r2, #1
; CHECK-NEXT:    mov r2, [r2+#.LJTI0_0]
; CHECK-NEXT:    jmpi cc_UC, [r2]
; CHECK-NEXT:  .LBB0_2: ; %a
; CHECK-NEXT:    mov r2, #10
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_3: ; %e
; CHECK-NEXT:    mov r2, #50
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_4: ; %c
; CHECK-NEXT:    mov r2, #30
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_5: ; %d
; CHECK-NEXT:    mov r2, #40
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_6: ; %b
; CHECK-NEXT:    mov r2, #20
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_7: ; %f
; CHECK-NEXT:    mov r2, #60
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_8: ; %def
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    ret
entry:
  switch i16 %x, label %def [
    i16 0, label %a
    i16 1, label %b
    i16 2, label %c
    i16 3, label %d
    i16 4, label %e
    i16 5, label %f
  ]
a: ret i16 10
b: ret i16 20
c: ret i16 30
d: ret i16 40
e: ret i16 50
f: ret i16 60
def: ret i16 0
}

; Too few and too far apart to be worth a table, so this stays a chain of
; compares.
define i16 @sparse(i16 %x) {
; CHECK-LABEL: sparse:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    cmp r2, #30000
; CHECK-NEXT:    jmpr cc_EQ, .LBB1_5
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    cmp r2, #1000
; CHECK-NEXT:    jmpr cc_EQ, .LBB1_4
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    cmp r2, #1
; CHECK-NEXT:    jmpr cc_NE, .LBB1_6
; CHECK-NEXT:  ; %bb.3: ; %a
; CHECK-NEXT:    mov r2, #1
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB1_4: ; %b
; CHECK-NEXT:    mov r2, #2
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB1_5: ; %c
; CHECK-NEXT:    mov r2, #3
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB1_6: ; %def
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    ret
entry:
  switch i16 %x, label %def [
    i16 1, label %a
    i16 1000, label %b
    i16 30000, label %c
  ]
a: ret i16 1
b: ret i16 2
c: ret i16 3
def: ret i16 0
}

; An indirect branch goes through the same JMPI.
define void @indirect(ptr %target) {
; CHECK-LABEL: indirect:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    jmpi cc_UC, [r2]
; CHECK-NEXT:  .LBB2_1: ; %y
; CHECK-NEXT:    ret
entry:
  indirectbr ptr %target, [label %x, label %y]
x: ret void
y: ret void
}
