; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

@g = global i16 42
@b = global i8 7

define i16 @load_absolute() {
; CHECK-LABEL: load_absolute:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, g
; CHECK-NEXT:    ret
  %v = load i16, ptr @g
  ret i16 %v
}

define void @store_absolute(i16 %x) {
; CHECK-LABEL: store_absolute:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov g, r2
; CHECK-NEXT:    ret
  store i16 %x, ptr @g
  ret void
}

define i16 @load_indirect(ptr %p) {
; CHECK-LABEL: load_indirect:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, [r2]
; CHECK-NEXT:    ret
  %v = load i16, ptr %p
  ret i16 %v
}

define i16 @load_displaced(ptr %p) {
; CHECK-LABEL: load_displaced:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, [r2+#8]
; CHECK-NEXT:    ret
  %a = getelementptr i16, ptr %p, i16 4
  %v = load i16, ptr %a
  ret i16 %v
}

define void @store_displaced(ptr %p, i16 %v) {
; CHECK-LABEL: store_displaced:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov [r2+#6], r3
; CHECK-NEXT:    ret
  %a = getelementptr i16, ptr %p, i16 3
  store i16 %v, ptr %a
  ret void
}

define i16 @load_indexed(ptr %p, i16 %i) {
; CHECK-LABEL: load_indexed:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    shl r3, #1
; CHECK-NEXT:    add r3, r2
; CHECK-NEXT:    mov r2, [r3+#0]
; CHECK-NEXT:    ret
  %a = getelementptr i16, ptr %p, i16 %i
  %v = load i16, ptr %a
  ret i16 %v
}

define ptr @address_of_global() {
; CHECK-LABEL: address_of_global:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, #g
; CHECK-NEXT:    ret
  ret ptr @g
}
