; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -mattr=+mac -verify-machineinstrs < %s | FileCheck %s

; A summing loop leaves its total in the coprocessor: the CoLOAD is in the
; preheader, the CoSTOREs are past the exit, and what is left going round is
; the CoMAC on its own.
;
; The accumulator is one register pair shared by the whole part and saved by
; nothing, so the loops below that could lose it keep the round trip they
; started with.

@a = global [64 x i16] zeroinitializer
@b = global [64 x i16] zeroinitializer

define i32 @chained(i32 %n) {
; CHECK-LABEL: chained:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov r4, #0
; CHECK-NEXT:    mov r5, #1
; CHECK-NEXT:    mov r6, #1
; CHECK-NEXT:    cmp r3, #0
; CHECK-NEXT:    jmpr cc_SGE, .LBB0_7
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    cmp r2, #0
; CHECK-NEXT:    jmpr cc_NE, .LBB0_8
; CHECK-NEXT:  .LBB0_2: ; %entry
; CHECK-NEXT:    cmp r3, #0
; CHECK-NEXT:    jmpr cc_NE, .LBB0_9
; CHECK-NEXT:  .LBB0_3: ; %entry
; CHECK-NEXT:    jb r5.0, .LBB0_10
; CHECK-NEXT:  .LBB0_4: ; %body.preheader
; CHECK-NEXT:    mov r5, #b
; CHECK-NEXT:    coload r4, r4
; CHECK-NEXT:    mov r6, #0
; CHECK-NEXT:  .LBB0_5: ; %body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov r7, r4
; CHECK-NEXT:    shl r7, #1
; CHECK-NEXT:    mov r8, #a
; CHECK-NEXT:    add r8, r7
; CHECK-NEXT:    add r7, r5
; CHECK-NEXT:    mov r7, [r7+#0]
; CHECK-NEXT:    mov r8, [r8+#0]
; CHECK-NEXT:    comac r8, r7
; CHECK-NEXT:    add r4, #1
; CHECK-NEXT:    addc r6, #0
; CHECK-NEXT:    mov r7, r6
; CHECK-NEXT:    xor r7, r3
; CHECK-NEXT:    mov r8, r4
; CHECK-NEXT:    xor r8, r2
; CHECK-NEXT:    or r8, r7
; CHECK-NEXT:    jmpr cc_NE, .LBB0_5
; CHECK-NEXT:  ; %bb.6:
; CHECK-NEXT:    costore r4, mal
; CHECK-NEXT:    costore r3, mah
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_7: ; %entry
; CHECK-NEXT:    mov r6, #0
; CHECK-NEXT:    cmp r2, #0
; CHECK-NEXT:    jmpr cc_EQ, .LBB0_2
; CHECK-NEXT:  .LBB0_8: ; %entry
; CHECK-NEXT:    mov r5, #0
; CHECK-NEXT:    cmp r3, #0
; CHECK-NEXT:    jmpr cc_EQ, .LBB0_3
; CHECK-NEXT:  .LBB0_9: ; %entry
; CHECK-NEXT:    mov r5, r6
; CHECK-NEXT:    jnb r5.0, .LBB0_4
; CHECK-NEXT:  .LBB0_10:
; CHECK-NEXT:    mov r3, #0
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    ret
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %body, label %done

body:
  %i = phi i32 [ %next, %body ], [ 0, %entry ]
  %acc = phi i32 [ %sum, %body ], [ 0, %entry ]
  %pa = getelementptr inbounds [64 x i16], ptr @a, i32 0, i32 %i
  %pb = getelementptr inbounds [64 x i16], ptr @b, i32 0, i32 %i
  %va = load i16, ptr %pa
  %vb = load i16, ptr %pb
  %sa = sext i16 %va to i32
  %sb = sext i16 %vb to i32
  %mul = mul nsw i32 %sa, %sb
  %sum = add nsw i32 %acc, %mul
  %next = add nuw nsw i32 %i, 1
  %at.end = icmp eq i32 %next, %n
  br i1 %at.end, label %done, label %body

done:
  %r = phi i32 [ 0, %entry ], [ %sum, %body ]
  ret i32 %r
}

; A call in the loop: the callee is free to multiply, and on a part with the
; coprocessor that is what multiplying uses.
declare void @sink(i32)

define i32 @has_call(i32 %n) {
; CHECK-LABEL: has_call:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sub r0, #12
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    mov [r0+#10], r1 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#8], r12 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#6], r13 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#4], r14 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#2], r15 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r1, -2
; CHECK-NEXT:    .cfi_offset r12, -4
; CHECK-NEXT:    .cfi_offset r13, -6
; CHECK-NEXT:    .cfi_offset r14, -8
; CHECK-NEXT:    .cfi_offset r15, -10
; CHECK-NEXT:    mov r14, r3
; CHECK-NEXT:    mov r12, r2
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    mov r6, #1
; CHECK-NEXT:    mov r3, #1
; CHECK-NEXT:    cmp r14, #0
; CHECK-NEXT:    jmpr cc_SGE, .LBB1_6
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    cmp r12, #0
; CHECK-NEXT:    jmpr cc_NE, .LBB1_7
; CHECK-NEXT:  .LBB1_2: ; %entry
; CHECK-NEXT:    cmp r14, #0
; CHECK-NEXT:    jmpr cc_NE, .LBB1_8
; CHECK-NEXT:  .LBB1_3: ; %entry
; CHECK-NEXT:    jb r6.0, .LBB1_9
; CHECK-NEXT:  .LBB1_4: ; %body.preheader
; CHECK-NEXT:    mov r1, #0
; CHECK-NEXT:    mov r13, #0
; CHECK-NEXT:    mov r15, #0
; CHECK-NEXT:  .LBB1_5: ; %body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov r6, r1
; CHECK-NEXT:    shl r6, #1
; CHECK-NEXT:    mov r3, #a
; CHECK-NEXT:    add r3, r6
; CHECK-NEXT:    mov r7, #b
; CHECK-NEXT:    add r6, r7
; CHECK-NEXT:    mov r6, [r6+#0]
; CHECK-NEXT:    mov r3, [r3+#0]
; CHECK-NEXT:    coload r2, r15
; CHECK-NEXT:    comac r3, r6
; CHECK-NEXT:    costore r2, mal
; CHECK-NEXT:    costore r15, mah
; CHECK-NEXT:    mov [r0], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    mov r3, r15
; CHECK-NEXT:    calla cc_UC, sink
; CHECK-NEXT:    mov r2, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    add r1, #1
; CHECK-NEXT:    addc r13, #0
; CHECK-NEXT:    mov r6, r13
; CHECK-NEXT:    xor r6, r14
; CHECK-NEXT:    mov r3, r1
; CHECK-NEXT:    xor r3, r12
; CHECK-NEXT:    or r3, r6
; CHECK-NEXT:    jmpr cc_NE, .LBB1_5
; CHECK-NEXT:    jmpr cc_UC, .LBB1_10
; CHECK-NEXT:  .LBB1_6: ; %entry
; CHECK-NEXT:    mov r3, #0
; CHECK-NEXT:    cmp r12, #0
; CHECK-NEXT:    jmpr cc_EQ, .LBB1_2
; CHECK-NEXT:  .LBB1_7: ; %entry
; CHECK-NEXT:    mov r6, #0
; CHECK-NEXT:    cmp r14, #0
; CHECK-NEXT:    jmpr cc_EQ, .LBB1_3
; CHECK-NEXT:  .LBB1_8: ; %entry
; CHECK-NEXT:    mov r6, r3
; CHECK-NEXT:    jnb r6.0, .LBB1_4
; CHECK-NEXT:  .LBB1_9:
; CHECK-NEXT:    mov r15, #0
; CHECK-NEXT:  .LBB1_10: ; %done
; CHECK-NEXT:    mov r3, r15
; CHECK-NEXT:    mov r15, [r0+#2] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r14, [r0+#4] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r13, [r0+#6] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r12, [r0+#8] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r1, [r0+#10] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #12
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    ret
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %body, label %done

body:
  %i = phi i32 [ %next, %body ], [ 0, %entry ]
  %acc = phi i32 [ %sum, %body ], [ 0, %entry ]
  %pa = getelementptr inbounds [64 x i16], ptr @a, i32 0, i32 %i
  %pb = getelementptr inbounds [64 x i16], ptr @b, i32 0, i32 %i
  %va = load i16, ptr %pa
  %vb = load i16, ptr %pb
  %sa = sext i16 %va to i32
  %sb = sext i16 %vb to i32
  %mul = mul nsw i32 %sa, %sb
  %sum = add nsw i32 %acc, %mul
  call void @sink(i32 %sum)
  %next = add nuw nsw i32 %i, 1
  %at.end = icmp eq i32 %next, %n
  br i1 %at.end, label %done, label %body

done:
  %r = phi i32 [ 0, %entry ], [ %sum, %body ]
  ret i32 %r
}

; The running total is read inside the loop, so the register pair still has to
; hold it each time round.
@seen = global i32 0

define i32 @reads_total(i32 %n) {
; CHECK-LABEL: reads_total:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov r4, #0
; CHECK-NEXT:    mov r5, #1
; CHECK-NEXT:    mov r6, #1
; CHECK-NEXT:    cmp r3, #0
; CHECK-NEXT:    jmpr cc_SGE, .LBB2_6
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    cmp r2, #0
; CHECK-NEXT:    jmpr cc_NE, .LBB2_7
; CHECK-NEXT:  .LBB2_2: ; %entry
; CHECK-NEXT:    cmp r3, #0
; CHECK-NEXT:    jmpr cc_NE, .LBB2_8
; CHECK-NEXT:  .LBB2_3: ; %entry
; CHECK-NEXT:    jb r5.0, .LBB2_9
; CHECK-NEXT:  .LBB2_4: ; %body.preheader
; CHECK-NEXT:    mov r6, #0
; CHECK-NEXT:    mov r7, #b
; CHECK-NEXT:    mov r8, #0
; CHECK-NEXT:    mov r5, #0
; CHECK-NEXT:  .LBB2_5: ; %body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov r9, r6
; CHECK-NEXT:    shl r9, #1
; CHECK-NEXT:    mov r10, #a
; CHECK-NEXT:    add r10, r9
; CHECK-NEXT:    add r9, r7
; CHECK-NEXT:    mov r9, [r9+#0]
; CHECK-NEXT:    mov r10, [r10+#0]
; CHECK-NEXT:    coload r4, r5
; CHECK-NEXT:    comac r10, r9
; CHECK-NEXT:    costore r4, mal
; CHECK-NEXT:    costore r5, mah
; CHECK-NEXT:    add r6, #1
; CHECK-NEXT:    addc r8, #0
; CHECK-NEXT:    mov r9, r8
; CHECK-NEXT:    xor r9, r3
; CHECK-NEXT:    mov r10, r6
; CHECK-NEXT:    xor r10, r2
; CHECK-NEXT:    mov seen+2, r5
; CHECK-NEXT:    mov seen, r4
; CHECK-NEXT:    or r10, r9
; CHECK-NEXT:    jmpr cc_NE, .LBB2_5
; CHECK-NEXT:    jmpr cc_UC, .LBB2_10
; CHECK-NEXT:  .LBB2_6: ; %entry
; CHECK-NEXT:    mov r6, #0
; CHECK-NEXT:    cmp r2, #0
; CHECK-NEXT:    jmpr cc_EQ, .LBB2_2
; CHECK-NEXT:  .LBB2_7: ; %entry
; CHECK-NEXT:    mov r5, #0
; CHECK-NEXT:    cmp r3, #0
; CHECK-NEXT:    jmpr cc_EQ, .LBB2_3
; CHECK-NEXT:  .LBB2_8: ; %entry
; CHECK-NEXT:    mov r5, r6
; CHECK-NEXT:    jnb r5.0, .LBB2_4
; CHECK-NEXT:  .LBB2_9:
; CHECK-NEXT:    mov r5, #0
; CHECK-NEXT:  .LBB2_10: ; %done
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    mov r3, r5
; CHECK-NEXT:    ret
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %body, label %done

body:
  %i = phi i32 [ %next, %body ], [ 0, %entry ]
  %acc = phi i32 [ %sum, %body ], [ 0, %entry ]
  %pa = getelementptr inbounds [64 x i16], ptr @a, i32 0, i32 %i
  %pb = getelementptr inbounds [64 x i16], ptr @b, i32 0, i32 %i
  %va = load i16, ptr %pa
  %vb = load i16, ptr %pb
  %sa = sext i16 %va to i32
  %sb = sext i16 %vb to i32
  %mul = mul nsw i32 %sa, %sb
  %sum = add nsw i32 %acc, %mul
  store volatile i32 %sum, ptr @seen
  %next = add nuw nsw i32 %i, 1
  %at.end = icmp eq i32 %next, %n
  br i1 %at.end, label %done, label %body

done:
  %r = phi i32 [ 0, %entry ], [ %sum, %body ]
  ret i32 %r
}
