; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; The C166 multiply/divide unit works through the MDL/MDH register pair.

define i16 @mul(i16 %a, i16 %b) {
; CHECK-LABEL: mul:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mul r2, r3
; CHECK-NEXT:    mov r2, mdl
; CHECK-NEXT:    ret
  %r = mul i16 %a, %b
  ret i16 %r
}

define i16 @sdiv(i16 %a, i16 %b) {
; CHECK-LABEL: sdiv:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov mdl, r2
; CHECK-NEXT:    div r3
; CHECK-NEXT:    mov r2, mdl
; CHECK-NEXT:    ret
  %r = sdiv i16 %a, %b
  ret i16 %r
}

define i16 @udiv(i16 %a, i16 %b) {
; CHECK-LABEL: udiv:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov mdl, r2
; CHECK-NEXT:    divu r3
; CHECK-NEXT:    mov r2, mdl
; CHECK-NEXT:    ret
  %r = udiv i16 %a, %b
  ret i16 %r
}

define i16 @srem(i16 %a, i16 %b) {
; CHECK-LABEL: srem:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov mdl, r2
; CHECK-NEXT:    div r3
; CHECK-NEXT:    mov r2, mdh
; CHECK-NEXT:    ret
  %r = srem i16 %a, %b
  ret i16 %r
}

define i16 @urem(i16 %a, i16 %b) {
; CHECK-LABEL: urem:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov mdl, r2
; CHECK-NEXT:    divu r3
; CHECK-NEXT:    mov r2, mdh
; CHECK-NEXT:    ret
  %r = urem i16 %a, %b
  ret i16 %r
}
