; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; Address space 2 is a far pointer that has been promised to stay inside one
; segment.  It is the same 32 bits as address space 1 and is accessed the same
; way - an EXTS naming the segment, then an ordinary access - so the only
; difference these tests can show is in the arithmetic: stepping one of these
; touches the low sixteen bits, and stepping a far pointer carries into the
; segment.  Each function below has its address space 1 twin beside it, which
; is where that difference is visible.
;
; The promise itself is in the data layout, which gives this address space an
; index size of sixteen; C166LowerSegPointers.cpp turns what that means into
; the arithmetic below.

@fg = addrspace(1) global [16 x i16] zeroinitializer
@sg = addrspace(2) global [16 x i16] zeroinitializer

; An access on its own is a far access, and identical to one.
define i16 @seg_load(ptr addrspace(2) %p) {
; CHECK-LABEL: seg_load:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov r2, [r2]
; CHECK-NEXT:    ret
  %v = load i16, ptr addrspace(2) %p
  ret i16 %v
}

define void @seg_store(ptr addrspace(2) %p, i16 %v) {
; CHECK-LABEL: seg_store:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov [r2], r4
; CHECK-NEXT:    ret
  store i16 %v, ptr addrspace(2) %p
  ret void
}

; A constant step: one add against an add and an add with carry.
define i16 @seg_offset(ptr addrspace(2) %p) {
; CHECK-LABEL: seg_offset:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r2, #8
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov r2, [r2]
; CHECK-NEXT:    ret
  %q = getelementptr i16, ptr addrspace(2) %p, i16 4
  %v = load i16, ptr addrspace(2) %q
  ret i16 %v
}

define i16 @far_offset(ptr addrspace(1) %p) {
; CHECK-LABEL: far_offset:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r2, #8
; CHECK-NEXT:    addc r3, #0
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov r2, [r2]
; CHECK-NEXT:    ret
  %q = getelementptr i16, ptr addrspace(1) %p, i32 4
  %v = load i16, ptr addrspace(1) %q
  ret i16 %v
}

; A variable index into a global, which is what an array subscript is.
define i16 @seg_index(i16 %i) {
; CHECK-LABEL: seg_index:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    shl r2, #1
; CHECK-NEXT:    mov r3, #sof(sg)
; CHECK-NEXT:    add r3, r2
; CHECK-NEXT:    exts #seg(sg), #1
; CHECK-NEXT:    mov r2, [r3]
; CHECK-NEXT:    ret
  %q = getelementptr [16 x i16], ptr addrspace(2) @sg, i16 0, i16 %i
  %v = load i16, ptr addrspace(2) %q
  ret i16 %v
}

; Walking an array, which is where the difference is worth having: the segment
; half of the pointer is only read, so the loop steps one register - and the
; step is folded into the access, which is MEM-3 and is worth two states an
; element on top.  seg-post-inc.ll is where that is checked on its own; here it
; is what the loop happens to look like.
define i16 @seg_walk(ptr addrspace(2) %p, i16 %n) {
; CHECK-LABEL: seg_walk:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov r5, r2
; CHECK-NEXT:    cmp r4, #0
; CHECK-NEXT:    jmpr cc_EQ, .LBB5_4
; CHECK-NEXT:  ; %bb.1: ; %body.preheader
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:  .LBB5_2: ; %body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov r6, [r5+]
; CHECK-NEXT:    add r2, r6
; CHECK-NEXT:    add r4, #-1
; CHECK-NEXT:    jmpr cc_NE, .LBB5_2
; CHECK-NEXT:  ; %bb.3: ; %done
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB5_4:
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    ret
entry:
  %c = icmp eq i16 %n, 0
  br i1 %c, label %done, label %body
body:
  %pp = phi ptr addrspace(2) [ %pn, %body ], [ %p, %entry ]
  %s = phi i16 [ %sn, %body ], [ 0, %entry ]
  %i = phi i16 [ %in, %body ], [ %n, %entry ]
  %v = load i16, ptr addrspace(2) %pp
  %sn = add i16 %s, %v
  %pn = getelementptr i16, ptr addrspace(2) %pp, i16 1
  %in = add i16 %i, -1
  %e = icmp eq i16 %in, 0
  br i1 %e, label %done, label %body
done:
  %r = phi i16 [ 0, %entry ], [ %sn, %body ]
  ret i16 %r
}

; The same loop over a far pointer, which is the measurement in the commit
; message: nine instructions against six, and the segment written every time
; round because the add might have carried into it.
define i16 @far_walk(ptr addrspace(1) %p, i16 %n) {
; CHECK-LABEL: far_walk:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov r5, r2
; CHECK-NEXT:    cmp r4, #0
; CHECK-NEXT:    jmpr cc_EQ, .LBB6_4
; CHECK-NEXT:  ; %bb.1: ; %body.preheader
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    mov r6, r5
; CHECK-NEXT:  .LBB6_2: ; %body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add r6, #2
; CHECK-NEXT:    exts r3, #1
; CHECK-NEXT:    mov r5, [r5]
; CHECK-NEXT:    addc r3, #0
; CHECK-NEXT:    add r2, r5
; CHECK-NEXT:    add r4, #-1
; CHECK-NEXT:    mov r5, r6
; CHECK-NEXT:    cmp r4, #0
; CHECK-NEXT:    jmpr cc_NE, .LBB6_2
; CHECK-NEXT:  ; %bb.3: ; %done
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB6_4:
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    ret
entry:
  %c = icmp eq i16 %n, 0
  br i1 %c, label %done, label %body
body:
  %pp = phi ptr addrspace(1) [ %pn, %body ], [ %p, %entry ]
  %s = phi i16 [ %sn, %body ], [ 0, %entry ]
  %i = phi i16 [ %in, %body ], [ %n, %entry ]
  %v = load i16, ptr addrspace(1) %pp
  %sn = add i16 %s, %v
  %pn = getelementptr i16, ptr addrspace(1) %pp, i32 1
  %in = add i16 %i, -1
  %e = icmp eq i16 %in, 0
  br i1 %e, label %done, label %body
done:
  %r = phi i16 [ 0, %entry ], [ %sn, %body ]
  ret i16 %r
}

; Dropping the promise costs nothing, because the representation is the same.
define ptr addrspace(1) @widen(ptr addrspace(2) %p) {
; CHECK-LABEL: widen:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ret
  %q = addrspacecast ptr addrspace(2) %p to ptr addrspace(1)
  ret ptr addrspace(1) %q
}

; And making it costs nothing either; what it costs is the obligation.
define ptr addrspace(2) @narrow(ptr addrspace(1) %p) {
; CHECK-LABEL: narrow:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ret
  %q = addrspacecast ptr addrspace(1) %p to ptr addrspace(2)
  ret ptr addrspace(2) %q
}

; A near pointer widens into one the same way it widens into a far pointer:
; the whole near space is segment 0 under the reset data page pointers.
define ptr addrspace(2) @from_near(ptr %p) {
; CHECK-LABEL: from_near:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r3, #0
; CHECK-NEXT:    ret
  %q = addrspacecast ptr %p to ptr addrspace(2)
  ret ptr addrspace(2) %q
}

; The symbol's own address is built from the same two relocations a far one is.
define ptr addrspace(2) @seg_address() {
; CHECK-LABEL: seg_address:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, #sof(sg)
; CHECK-NEXT:    mov r3, #seg(sg)
; CHECK-NEXT:    ret
  ret ptr addrspace(2) @sg
}

; And a global in this space is placed where a far one is: outside segment 0,
; where near addressing cannot reach it.
; CHECK: .section .farbss
; CHECK: sg:
