; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

define i16 @select_umax(i16 %a, i16 %b) {
; CHECK-LABEL: select_umax:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    cmp r2, r3
; CHECK-NEXT:    jmpa cc_UGT, .LBB0_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    mov r2, r3
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    ret
  %c = icmp ugt i16 %a, %b
  %r = select i1 %c, i16 %a, i16 %b
  ret i16 %r
}

define i8 @select_byte(i8 %a, i8 %b, i16 %x) {
; CHECK-LABEL: select_byte:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r5, #0
; CHECK-NEXT:    cmp r4, r5
; CHECK-NEXT:    jmpa cc_EQ, .LBB1_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    movb rl2, rl3
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    ret
  %c = icmp eq i16 %x, 0
  %r = select i1 %c, i8 %a, i8 %b
  ret i8 %r
}

define i16 @setcc_sge(i16 %a, i16 %b) {
; CHECK-LABEL: setcc_sge:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    mov r2, #1
; CHECK-NEXT:    cmp r4, r3
; CHECK-NEXT:    jmpa cc_SGE, .LBB2_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    ret
  %c = icmp sge i16 %a, %b
  %z = zext i1 %c to i16
  ret i16 %z
}
