; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

define i16 @shl_imm(i16 %a) {
; CHECK-LABEL: shl_imm:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    shl r2, #3
; CHECK-NEXT:    ret
  %r = shl i16 %a, 3
  ret i16 %r
}

define i16 @shl_reg(i16 %a, i16 %b) {
; CHECK-LABEL: shl_reg:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    shl r2, r3
; CHECK-NEXT:    ret
  %r = shl i16 %a, %b
  ret i16 %r
}

define i16 @lshr_imm(i16 %a) {
; CHECK-LABEL: lshr_imm:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    shr r2, #5
; CHECK-NEXT:    ret
  %r = lshr i16 %a, 5
  ret i16 %r
}

define i16 @ashr_reg(i16 %a, i16 %b) {
; CHECK-LABEL: ashr_reg:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ashr r2, r3
; CHECK-NEXT:    ret
  %r = ashr i16 %a, %b
  ret i16 %r
}

define i16 @rotl(i16 %x, i16 %n) {
; CHECK-LABEL: rotl:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    rol r2, r3
; CHECK-NEXT:    ret
  %a = shl i16 %x, %n
  %s = sub i16 16, %n
  %b = lshr i16 %x, %s
  %r = or i16 %a, %b
  ret i16 %r
}
