; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=c166 -filetype=obj < %s -o %t.o
; RUN: llvm-objdump -d %t.o | FileCheck %s --check-prefix=BYTES

; Several addressing modes come in a two byte and a four byte form.  A bare
; [Rw], a constant of 0 to 15 in a MOV and a constant of 0 to 7 in an
; arithmetic instruction all take the short one.

define i16 @load_indirect(ptr %p) {
; CHECK-LABEL: load_indirect:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, [r2]
; CHECK-NEXT:    ret
  %v = load i16, ptr %p
  ret i16 %v
}

define void @store_indirect(ptr %p, i16 %v) {
; CHECK-LABEL: store_indirect:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov [r2], r3
; CHECK-NEXT:    ret
  store i16 %v, ptr %p
  ret void
}

define i16 @small_constant() {
; CHECK-LABEL: small_constant:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, #15
; CHECK-NEXT:    ret
  ret i16 15
}

define i16 @constant_too_big() {
; CHECK-LABEL: constant_too_big:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r2, #16
; CHECK-NEXT:    ret
  ret i16 16
}

define i16 @small_add(i16 %a) {
; CHECK-LABEL: small_add:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r2, #7
; CHECK-NEXT:    ret
  %r = add i16 %a, 7
  ret i16 %r
}

define i16 @add_too_big(i16 %a) {
; CHECK-LABEL: add_too_big:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r2, #8
; CHECK-NEXT:    ret
  %r = add i16 %a, 8
  ret i16 %r
}

; A pointer walk is where it adds up: the loop body is all short forms, and the
; pointer steps itself as part of the load rather than needing its own add.
define i16 @sum(ptr %a, i16 %n) {
; CHECK-LABEL: sum:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    mov r2, #0
; CHECK-NEXT:    mov r5, #0
; CHECK-NEXT:  .LBB6_1: ; %loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov r6, [r4+]
; CHECK-NEXT:    add r2, r6
; CHECK-NEXT:    add r5, #1
; CHECK-NEXT:    cmp r5, r3
; CHECK-NEXT:    jmpr cc_ULT, .LBB6_1
; CHECK-NEXT:  ; %bb.2: ; %done
; CHECK-NEXT:    ret
entry:
  br label %loop
loop:
  %i = phi i16 [0, %entry], [%i1, %loop]
  %s = phi i16 [0, %entry], [%s1, %loop]
  %p = getelementptr i16, ptr %a, i16 %i
  %v = load i16, ptr %p
  %s1 = add i16 %s, %v
  %i1 = add i16 %i, 1
  %c = icmp ult i16 %i1, %n
  br i1 %c, label %loop, label %done
done:
  ret i16 %s1
}

define i8 @walk_bytes(ptr %a, i16 %n) {
; CHECK-LABEL: walk_bytes:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    movb rl2, #0
; CHECK-NEXT:    mov r5, #0
; CHECK-NEXT:  .LBB7_1: ; %loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov r6, r4
; CHECK-NEXT:    add r6, r5
; CHECK-NEXT:    movb rl6, [r6]
; CHECK-NEXT:    addb rl2, rl6
; CHECK-NEXT:    add r5, #1
; CHECK-NEXT:    cmp r5, r3
; CHECK-NEXT:    jmpr cc_ULT, .LBB7_1
; CHECK-NEXT:  ; %bb.2: ; %done
; CHECK-NEXT:    ret
entry:
  br label %loop
loop:
  %i = phi i16 [0, %entry], [%i1, %loop]
  %s = phi i8 [0, %entry], [%s1, %loop]
  %p = getelementptr i8, ptr %a, i16 %i
  %v = load i8, ptr %p
  %s1 = add i8 %s, %v
  %i1 = add i16 %i, 1
  %c = icmp ult i16 %i1, %n
  br i1 %c, label %loop, label %done
done:
  ret i8 %s1
}

; BYTES-LABEL: <load_indirect>:
; BYTES-NEXT:    a8 22
; BYTES-LABEL: <store_indirect>:
; BYTES-NEXT:    b8 32
; BYTES-LABEL: <small_constant>:
; BYTES-NEXT:    e0 f2
; BYTES-LABEL: <constant_too_big>:
; BYTES-NEXT:    e6 f2 10 00
; BYTES-LABEL: <small_add>:
; BYTES-NEXT:    08 27
; BYTES-LABEL: <add_too_big>:
; BYTES-NEXT:    06 f2 08 00
