; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; A tail call jumps to the callee once this function's frame is gone, so the
; callee's RET goes straight back to our caller and no return address is ever
; pushed onto the small hardware stack.

declare i16 @callee(i16, i16)
declare void @vcallee()
declare i16 @many(i16, i16, i16, i16, i16, i16)
declare i16 @far_callee(i16) #1

define i16 @simple(i16 %a, i16 %b) {
; CHECK-LABEL: simple:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    jmpa cc_UC, callee
  %r = tail call i16 @callee(i16 %a, i16 %b)
  ret i16 %r
}

define void @returns_void() {
; CHECK-LABEL: returns_void:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    jmpa cc_UC, vcallee
  tail call void @vcallee()
  ret void
}

; The frame comes down in front of the jump.
define i16 @with_frame(i16 %a) {
; CHECK-LABEL: with_frame:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r0, #2
; CHECK-NEXT:    .cfi_def_cfa_offset 2
; CHECK-NEXT:    mov [r0], r2
; CHECK-NEXT:    mov r3, #1
; CHECK-NEXT:    add r0, #2
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    jmpa cc_UC, callee
  %p = alloca i16
  store i16 %a, ptr %p
  %v = load i16, ptr %p
  %r = tail call i16 @callee(i16 %v, i16 1)
  ret i16 %r
}

define i16 @indirect(ptr %f, i16 %a) {
; CHECK-LABEL: indirect:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    mov r2, r3
; CHECK-NEXT:    mov r3, #2
; CHECK-NEXT:    jmpi cc_UC, [r4]
  %r = tail call i16 %f(i16 %a, i16 2)
  ret i16 %r
}

; A call whose result is used again is not in tail position.
define i16 @not_in_tail_position(i16 %a) {
; CHECK-LABEL: not_in_tail_position:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r3, #1
; CHECK-NEXT:    calla cc_UC, callee
; CHECK-NEXT:    add r2, #1
; CHECK-NEXT:    ret
  %r = call i16 @callee(i16 %a, i16 1)
  %s = add i16 %r, 1
  ret i16 %s
}

; An interrupt handler comes back with RETI, which the callee's RET is not.
define i16 @from_interrupt(i16 %a) #0 {
; CHECK-LABEL: from_interrupt:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    push mdc
; CHECK-NEXT:    push mdl
; CHECK-NEXT:    push mdh
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x08, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x06, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x0c ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x08 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x0a ; caller's PSW
; CHECK-NEXT:    sub r0, #20
; CHECK-NEXT:    .cfi_def_cfa_offset 20
; CHECK-NEXT:    mov [r0+#18], r2 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#16], r3 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#14], r4 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#12], r5 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#10], r6 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#8], r7 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#6], r8 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#4], r9 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0+#2], r10 ; 2-byte Folded Spill
; CHECK-NEXT:    mov [r0], r11 ; 2-byte Folded Spill
; CHECK-NEXT:    .cfi_offset r2, -2
; CHECK-NEXT:    .cfi_offset r3, -4
; CHECK-NEXT:    .cfi_offset r4, -6
; CHECK-NEXT:    .cfi_offset r5, -8
; CHECK-NEXT:    .cfi_offset r6, -10
; CHECK-NEXT:    .cfi_offset r7, -12
; CHECK-NEXT:    .cfi_offset r8, -14
; CHECK-NEXT:    .cfi_offset r9, -16
; CHECK-NEXT:    .cfi_offset r10, -18
; CHECK-NEXT:    .cfi_offset r11, -20
; CHECK-NEXT:    mov r3, #1
; CHECK-NEXT:    calla cc_UC, callee
; CHECK-NEXT:    mov r11, [r0] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r10, [r0+#2] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r9, [r0+#4] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r8, [r0+#6] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r7, [r0+#8] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r6, [r0+#10] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r5, [r0+#12] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r4, [r0+#14] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r3, [r0+#16] ; 2-byte Folded Reload
; CHECK-NEXT:    mov r2, [r0+#18] ; 2-byte Folded Reload
; CHECK-NEXT:    add r0, #20
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    pop mdh
; CHECK-NEXT:    pop mdl
; CHECK-NEXT:    pop mdc
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x06 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    .cfi_escape 0x10, 0x20, 0x03, 0x92, 0x24, 0x04 ; caller's PSW
; CHECK-NEXT:    reti
  %r = tail call i16 @callee(i16 %a, i16 1)
  ret i16 %r
}

; Arguments beyond the four that go in registers would be written where the
; frame is about to stop being.
define i16 @stack_arguments(i16 %a) {
; CHECK-LABEL: stack_arguments:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r3, #1
; CHECK-NEXT:    mov r4, #2
; CHECK-NEXT:    mov r5, #3
; CHECK-NEXT:    mov r6, #4
; CHECK-NEXT:    mov r7, #5
; CHECK-NEXT:    jmpa cc_UC, many
  %r = tail call i16 @many(i16 %a, i16 1, i16 2, i16 3, i16 4, i16 5)
  ret i16 %r
}

; Both ends have to be the same kind, since a near callee's RET would pop half
; of what a far caller left on the hardware stack and a far callee's RETS would
; pop a segment a near caller never pushed.
define i16 @to_far(i16 %a) {
; CHECK-LABEL: to_far:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    calls #seg(far_callee), sof(far_callee)
; CHECK-NEXT:    ret
  %r = tail call i16 @far_callee(i16 %a)
  ret i16 %r
}

define i16 @from_far(i16 %a) #1 {
; CHECK-LABEL: from_far:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x04 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    mov r3, #1
; CHECK-NEXT:    calla cc_UC, callee
; CHECK-NEXT:    rets
  %r = tail call i16 @callee(i16 %a, i16 1)
  ret i16 %r
}

; Far to far goes through JMPS, which names the target segment; JMPA would only
; reach inside the segment this function happens to have been called into.
declare i16 @far_many(i16, i16, i16, i16, i16, i16) #1

define i16 @far_to_far(i16 %a) #1 {
; CHECK-LABEL: far_to_far:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x04 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    jmps #seg(far_callee), sof(far_callee)
  %r = tail call i16 @far_callee(i16 %a)
  ret i16 %r
}

; There is no inter-segment CALLI, so no indirect far jump to tail call
; through either.
define i16 @far_indirect(ptr %f, i16 %a) #1 {
; CHECK-LABEL: far_indirect:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x04 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    mov r2, r3
; CHECK-NEXT:    calli cc_UC, [r4]
; CHECK-NEXT:    rets
  %r = tail call i16 %f(i16 %a)
  ret i16 %r
}

define i16 @far_stack_arguments(i16 %a) #1 {
; CHECK-LABEL: far_stack_arguments:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    .cfi_escape 0x16, 0x2d, 0x0e, 0x92, 0x24, 0x02, 0x94, 0x02, 0x08, 0x10, 0x24, 0x92, 0x24, 0x00, 0x94, 0x02, 0x21 ; return address, from the hardware stack
; CHECK-NEXT:    .cfi_escape 0x16, 0x24, 0x03, 0x92, 0x24, 0x04 ; caller's hardware stack pointer
; CHECK-NEXT:    .cfi_escape 0x10, 0x2c, 0x03, 0x92, 0x24, 0x02 ; caller's CSP
; CHECK-NEXT:    mov r3, #1
; CHECK-NEXT:    mov r4, #2
; CHECK-NEXT:    mov r5, #3
; CHECK-NEXT:    mov r6, #4
; CHECK-NEXT:    mov r7, #5
; CHECK-NEXT:    jmps #seg(far_many), sof(far_many)
  %r = tail call i16 @far_many(i16 %a, i16 1, i16 2, i16 3, i16 4, i16 5)
  ret i16 %r
}

attributes #0 = { "interrupt" }
attributes #1 = { "far" }
