; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; Variadic functions receive every argument on the stack so that the callee can
; walk the list with a plain pointer.

declare void @llvm.va_start(ptr)
declare void @llvm.va_end(ptr)

define i16 @first_vararg(i16 %n, ...) {
; CHECK-LABEL: first_vararg:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r0, #2
; CHECK-NEXT:    .cfi_def_cfa_offset 2
; CHECK-NEXT:    mov r2, r0
; CHECK-NEXT:    add r2, #4
; CHECK-NEXT:    mov [r0], r2
; CHECK-NEXT:    mov r2, [r0+#4]
; CHECK-NEXT:    add r0, #2
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    ret
  %ap = alloca ptr
  call void @llvm.va_start(ptr %ap)
  %p = load ptr, ptr %ap
  %v = load i16, ptr %p
  call void @llvm.va_end(ptr %ap)
  ret i16 %v
}

declare i16 @variadic(i16, ...)

define i16 @call_variadic() {
; CHECK-LABEL: call_variadic:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub r0, #6
; CHECK-NEXT:    .cfi_def_cfa_offset 6
; CHECK-NEXT:    mov r2, #3
; CHECK-NEXT:    mov [r0+#4], r2
; CHECK-NEXT:    mov r2, #2
; CHECK-NEXT:    mov [r0+#2], r2
; CHECK-NEXT:    mov r2, #1
; CHECK-NEXT:    mov [r0], r2
; CHECK-NEXT:    calla cc_UC, variadic
; CHECK-NEXT:    add r0, #6
; CHECK-NEXT:    .cfi_def_cfa r0, 0
; CHECK-NEXT:    ret
  %r = call i16 (i16, ...) @variadic(i16 1, i16 2, i16 3)
  ret i16 %r
}
