; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=c166 -verify-machineinstrs < %s | FileCheck %s

; Anything wider than a word is split into 16 bit pieces; 32 bit multiplies use
; the hardware multiplier, division becomes a library call.

define i32 @add32(i32 %a, i32 %b) {
; CHECK-LABEL: add32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r4, r2
; CHECK-NEXT:    mov r6, #1
; CHECK-NEXT:    cmp r4, r2
; CHECK-NEXT:    jmpa cc_ULT, .LBB0_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    mov r6, #0
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    add r3, r5
; CHECK-NEXT:    add r3, r6
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    ret
  %r = add i32 %a, %b
  ret i32 %r
}

define i32 @mul32(i32 %a, i32 %b) {
; CHECK-LABEL: mul32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mul r2, r5
; CHECK-NEXT:    mov r5, mdl
; CHECK-NEXT:    mulu r2, r4
; CHECK-NEXT:    mov r6, mdh
; CHECK-NEXT:    add r6, r5
; CHECK-NEXT:    mul r3, r4
; CHECK-NEXT:    mov r3, mdl
; CHECK-NEXT:    add r3, r6
; CHECK-NEXT:    mul r2, r4
; CHECK-NEXT:    mov r2, mdl
; CHECK-NEXT:    ret
  %r = mul i32 %a, %b
  ret i32 %r
}

define i32 @sdiv32(i32 %a, i32 %b) {
; CHECK-LABEL: sdiv32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    calla cc_UC, __divsi3
; CHECK-NEXT:    ret
  %r = sdiv i32 %a, %b
  ret i32 %r
}

define i32 @shl32(i32 %a) {
; CHECK-LABEL: shl32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    shl r3, #1
; CHECK-NEXT:    mov r4, r2
; CHECK-NEXT:    shr r4, #15
; CHECK-NEXT:    or r3, r4
; CHECK-NEXT:    shl r2, #1
; CHECK-NEXT:    ret
  %r = shl i32 %a, 1
  ret i32 %r
}
