#!/usr/bin/env python3
"""Generate a random C program for the differential tests.

The hand written programs in this directory cover what someone thought of.
This covers what nobody did: given a seed it emits a program that computes a
number and prints it, and the same program compiled for the host and for the
C166 has to print the same thing.  A seed that disagrees is a reproducer.

Two things every generated program has to avoid, or the disagreement is the
generator's fault rather than the compiler's.

Undefined behaviour, because two compilers are entitled to disagree about it
and neither is wrong.  So: all arithmetic is unsigned and therefore wraps
rather than overflowing, every divisor has a bit forced into it, every shift
count is masked to the width being shifted, and nothing is read before it is
written.

And integer promotion, which is the subtler one.  Promotion stops at int, and
int is sixteen bits on the C166 and thirty two on the host, so "a * b" on two
u16 is computed in sixteen bits on one machine and thirty two on the other -
the same program with two meanings.  Every operation here is therefore written
with both operands cast to a width that promotes the same way on both, and the
result cast back to where it is going.  u32 and u64 are the only widths with
that property, which is why they are the only ones anything is computed in.
"""

import argparse
import random

# The types a value can have.  Only unsigned ones are stored, since signed
# overflow is undefined; a signed view is taken where an operation wants one.
TYPES = ["u8", "u16", "u32", "u64"]
WIDTH = {"u8": 8, "u16": 16, "u32": 32, "u64": 64}
# What each is computed in.  Anything narrower than u32 promotes differently on
# the two machines, so it is widened first and truncated after.
COMPUTE = {"u8": "u32", "u16": "u32", "u32": "u32", "u64": "u64"}
SIGNED = {"u32": "s32", "u64": "s64"}

PREAMBLE = """\
/* Generated by generate.py --seed %d.  Do not edit; regenerate.
   Compiled twice - once for c166 and run in the simulator, once for the host
   and run natively - and the two outputs must match exactly. */
#ifdef __c166__
static void put(char c) { *(__far volatile unsigned char *)0xFF0000 = c; }
#else
#include <stdio.h>
static void put(char c) { putchar(c); }
#endif

typedef __UINT8_TYPE__ u8;   typedef __INT8_TYPE__ s8;
typedef __UINT16_TYPE__ u16; typedef __INT16_TYPE__ s16;
typedef __UINT32_TYPE__ u32; typedef __INT32_TYPE__ s32;
typedef __UINT64_TYPE__ u64; typedef __INT64_TYPE__ s64;

static void puthex(u32 v, int d) {
  for (int i = d - 1; i >= 0; i--) put("0123456789abcdef"[(v >> (i*4)) & 0xF]);
  put('\\n');
}
"""


class Generator:
    def __init__(self, seed, functions, statements, depth, allow64):
        self.rnd = random.Random(seed)
        self.seed = seed
        self.functions = functions
        self.statements = statements
        self.depth = depth
        self.types = TYPES if allow64 else TYPES[:-1]
        self.out = []
        self.helpers = []      # (name, [(type, param)], return type)
        self.temp = 0

    # -- expressions ---------------------------------------------------

    def literal(self, ty):
        """A constant, weighted towards the values that are edges of a width:
        zero, one, all ones, the sign bit, and the boundaries either side."""
        w = WIDTH[ty]
        edges = [0, 1, 2, (1 << w) - 1, (1 << (w - 1)), (1 << (w - 1)) - 1,
                 (1 << (w // 2)) - 1, 1 << (w // 2)]
        if self.rnd.random() < 0.6:
            v = self.rnd.choice(edges)
        else:
            v = self.rnd.getrandbits(w)
        return "(%s)0x%xu%s" % (ty, v, "ll" if w == 64 else "")

    def convert(self, expr, frm, to):
        """A value of one width seen as another.  Truncation and zero
        extension are both well defined, so this needs no guarding."""
        return "(%s)(%s)" % (to, expr) if frm != to else expr

    def expr(self, ty, vars, depth):
        """An expression of type ty.  Every operation is computed in a width
        that promotes identically on both machines and truncated back."""
        if depth <= 0 or self.rnd.random() < 0.25:
            choices = [v for v in vars if vars[v] == ty]
            if choices and self.rnd.random() < 0.7:
                return self.rnd.choice(choices)
            # A variable of another width, converted.
            if vars and self.rnd.random() < 0.5:
                v = self.rnd.choice(list(vars))
                return self.convert(v, vars[v], ty)
            return self.literal(ty)

        c = COMPUTE[ty]
        s = SIGNED[c]
        mask = WIDTH[c] - 1
        kind = self.rnd.choice([
            "add", "sub", "mul", "and", "or", "xor", "not", "neg",
            "udiv", "umod", "shl", "shr", "sar", "ucmp", "scmp", "sel",
        ])

        def sub(t=None):
            return self.expr(t or ty, vars, depth - 1)

        a = self.convert(sub(), ty, c)
        if kind in ("not", "neg"):
            op = "~" if kind == "not" else "-"
            return "(%s)(%s%s)" % (ty, op, a)

        b = self.convert(sub(), ty, c)
        if kind in ("add", "sub", "mul", "and", "or", "xor"):
            op = {"add": "+", "sub": "-", "mul": "*",
                  "and": "&", "or": "|", "xor": "^"}[kind]
            return "(%s)(%s %s %s)" % (ty, a, op, b)
        if kind in ("udiv", "umod"):
            # A bit is forced into the divisor rather than testing it, so the
            # shape of the expression does not depend on its value.
            op = "/" if kind == "udiv" else "%"
            return "(%s)(%s %s (%s | 1))" % (ty, a, op, b)
        if kind in ("shl", "shr"):
            op = "<<" if kind == "shl" else ">>"
            return "(%s)(%s %s (%s & %d))" % (ty, a, op, b, mask)
        if kind == "sar":
            # An arithmetic shift, which is the one place a signed value is
            # useful: both compilers shift the sign bit in.
            return "(%s)((%s)%s >> (%s & %d))" % (ty, s, a, b, mask)
        if kind in ("ucmp", "scmp"):
            op = self.rnd.choice(["<", "<=", ">", ">=", "==", "!="])
            if kind == "ucmp":
                return "(%s)(%s %s %s)" % (ty, a, op, b)
            return "(%s)((%s)%s %s (%s)%s)" % (ty, s, a, op, s, b)
        # A select, which on this target is a fused compare and branch.
        return "(%s)(%s ? %s : %s)" % (ty, self.convert(sub(), ty, c), a, b)

    # -- statements ----------------------------------------------------

    def emit(self, line, indent):
        self.out.append("  " * indent + line)

    def block(self, vars, writable, budget, indent, depth):
        """A run of statements, which may nest.  vars is everything that can be
        read; writable is the subset that may be assigned to, which leaves out
        the loop counters - assigning to one of those could stop a loop ever
        finishing."""
        while budget > 0:
            budget -= 1
            r = self.rnd.random()
            if r < 0.50 or indent > 2 or not self.helpers:
                v = self.rnd.choice(writable)
                self.emit("%s = %s;" % (v, self.expr(vars[v], vars, depth)),
                          indent)
            elif r < 0.65:
                cond = self.expr("u32", vars, min(depth, 2))
                self.emit("if (%s) {" % cond, indent)
                budget = self.block(vars, writable, min(budget, 3),
                                    indent + 1, depth)
                self.emit("} else {", indent)
                budget = self.block(vars, writable, min(budget, 3),
                                    indent + 1, depth)
                self.emit("}", indent)
            elif r < 0.80:
                # A counted loop, so it always terminates.
                self.temp += 1
                i = "i%d" % self.temp
                n = self.rnd.randint(2, 6)
                self.emit("for (u32 %s = 0; %s < %d; %s++) {" % (i, i, n, i),
                          indent)
                inner = dict(vars)
                inner[i] = "u32"
                budget = self.block(inner, writable, min(budget, 4),
                                    indent + 1, depth)
                self.emit("}", indent)
            else:
                self.emit(self.call(vars, writable, depth), indent)
            self.emit("h = h * 31 + (u32)%s;" % self.rnd.choice(list(vars)),
                      indent)
        return budget

    # -- functions -----------------------------------------------------

    def call(self, vars, writable, depth):
        """A call to a helper that already exists.  Only backwards, so the call
        graph is acyclic and nothing can recurse without a base case."""
        name, params, ret = self.rnd.choice(self.helpers)
        args = ", ".join(self.expr(t, vars, min(depth, 2)) for t, _ in params)
        same = [k for k in writable if vars[k] == ret]
        v = self.rnd.choice(same or writable)
        cast = "" if vars[v] == ret else "(%s)" % vars[v]
        return "%s = %s%s(%s);" % (v, cast, name, args)

    def helper(self, index):
        """A function with enough arguments that some arrive on the stack."""
        n = self.rnd.randint(1, 8)
        params = [(self.rnd.choice(self.types), "p%d" % i) for i in range(n)]
        ret = self.rnd.choice(self.types)
        name = "fn%d" % index

        decl = ", ".join("%s %s" % (t, p) for t, p in params)
        self.emit("static %s %s(%s) {" % (ret, name, decl), 0)
        vars = {p: t for t, p in params}
        vars["r"] = ret
        self.emit("%s r = %s;" % (ret, self.literal(ret)), 1)
        self.emit("u32 h = 0;", 1)
        self.block(vars, list(vars), self.rnd.randint(2, 5), 1, self.depth)
        self.emit("return (%s)((%s)r + (%s)h);" % (ret, COMPUTE[ret],
                                                   COMPUTE[ret]), 1)
        self.emit("}", 0)
        self.emit("", 0)

        # Appended only now, so that the body above could not call it.
        self.helpers.append((name, params, ret))

    # -- the whole program ---------------------------------------------

    def generate(self):
        self.out.append(PREAMBLE % self.seed)

        # Globals, so that some values live in memory rather than registers.
        globals_ = {}
        for i in range(4):
            t = self.rnd.choice(self.types)
            name = "g%d" % i
            globals_[name] = t
            self.emit("static %s %s = %s;" % (t, name, self.literal(t)), 0)
        self.emit("", 0)

        # Helpers have to exist before they are called.
        for i in range(self.functions):
            self.helper(i)

        self.emit("int main(void) {", 0)
        self.emit("u32 h = 0;", 1)
        vars = dict(globals_)
        for i in range(6):
            t = self.rnd.choice(self.types)
            name = "v%d" % i
            vars[name] = t
            self.emit("%s %s = %s;" % (t, name, self.literal(t)), 1)
        # Printed in a few pieces rather than once at the end, so that a
        # disagreement says roughly where it started.
        for part in range(3):
            self.block(vars, list(vars), self.statements // 3, 1, self.depth)
            self.emit("puthex(h, 8);", 1)
        for v in sorted(vars):
            self.emit("h = h * 31 + (u32)%s;" % v, 1)
        self.emit("puthex(h, 8);", 1)
        self.emit("return 0;", 1)
        self.emit("}", 0)
        return "\n".join(self.out) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--seed", type=int, required=True)
    p.add_argument("--functions", type=int, default=4,
                   help="how many helper functions to generate")
    p.add_argument("--statements", type=int, default=14,
                   help="roughly how many statements main() gets")
    p.add_argument("--depth", type=int, default=4,
                   help="how deeply expressions nest")
    p.add_argument("--no-64", action="store_true",
                   help="leave out 64 bit types, which are libcalls and bulk")
    args = p.parse_args()
    print(Generator(args.seed, args.functions, args.statements, args.depth,
                    not args.no_64).generate(), end="")


if __name__ == "__main__":
    main()
